const mongoose = require('mongoose');

const questionSchema = new mongoose.Schema({
  questionType: {
    type: String,
    enum: ['MCQ', 'Coding', 'TrueFalse', 'FillInBlank'],
    required: true,
  },
  difficulty: {
    type: String,
    enum: ['easy', 'medium', 'hard'],
    default: 'easy',
  },
  questionText: {
    type: String,
    required: true,
  },
  // Category/Tags for better organization
  category: {
    type: String,
    enum: ['React', 'Python', 'JavaScript', 'DSA', 'General', 'Database', 'System Design'],
    default: 'General',
  },
  tags: [{
    type: String,
  }],
  // Points for this question
  points: {
    type: Number,
    default: 1,
  },
  // Time limit for this specific question (in seconds)
  timeLimit: {
    type: Number,
    default: 300, // 5 minutes default
  },
  // Explanation shown after test completion
  explanation: {
    type: String,
  },
  // For MCQs
  options: [{
    type: String,
  }],
  correctAnswer: {
    type: String,
  },
  // For multiple correct answers
  multipleCorrectAnswers: [{
    type: String,
  }],
  // For Coding Questions
  sampleInput: {
    type: String,
  },
  sampleOutput: {
    type: String,
  },
  testCases: [{
    input: String,
    output: String,
    isHidden: { type: Boolean, default: false }, // Hidden test cases
  }],
  // Starter code for coding questions
  starterCode: {
    type: String,
  },
  // Language for coding questions
  programmingLanguage: {
    type: String,
    enum: ['python', 'javascript', 'java', 'cpp'],
    default: 'python',
  },
  // Is this question active?
  isActive: {
    type: Boolean,
    default: true,
  },
  // Was this question generated by AI?
  isAIGenerated: {
    type: Boolean,
    default: false,
  },
}, {
  timestamps: true,
});

// Index for faster queries
questionSchema.index({ category: 1, difficulty: 1, isActive: 1 });

const Question = mongoose.model('Question', questionSchema);

module.exports = Question;
